### ISSUE TITLE
comply with BIRS formatting rules?

### ISSUE THREAD

**Issue by papsti** [davidearn/birs-2023-workshop-report#6]
@davidearn, I have some questions about formatting the workshop report that I wanted to run by you before asking BIRS. 

I took a closer look at comments in [`birs-2023-workshop-report/birs-shell.tex`](https://github.com/davidearn/birs-2023-workshop-report/blob/main/birs-shell.tex), which seem to suggest that BIRS uses this $\LaTeX$ template to collate reports together into a larger document. As a result, there are a few formatting rules they outline in the comments that we haven't been abiding by, namely:

```
%%  Please uncomment any package you need to use.
%%
%%  If you need to use any additional packages please email BIRS
%%   Programme Coordinator, birs@birs.ca, first.
%%
%%  \usepackage{epsfig}
%%
%%  \usepackage{amssymb}
%%
%%  \usepackage{amsmath}
%%
%%  \usepackage{amsthm}
%%
%%  \usepackage{graphics}
%%
```
and
```
%%  The use of TeX/LaTeX macros is NOT permitted.  Reports with macros
%%  will not be accepted.
%%
%%  Please let LaTeX handle the numbering of your sections, equations,
%%  figures and tables.
```
(We've used additional packages, macros, and `cleveref` to modify section numbering and various refs.)

However, the comments also state that the shell doc was last revised 24 March 2006, so I'm not sure whether it's still the case that they need us to abide by these rules (especially since the reports seem to be published online in a standalone way). 

Can you let me know if you remember having to abide by these formatting rules the last time you wrote a BIRS report?

**Comment by davidearn** [comment]
@papsti I could have sworn I replied to this, but apparently not!  We should not worry about this.  We should just do what is convenient for us and let them complain if they want to.  It is silly for us to spend any time making modifications based on some comments written 18 years ago.

**Comment by papsti** [comment]
good point!
